# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1282, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mplWidget = QtWidgets.QWidget(self.centralwidget)
        self.mplWidget.setGeometry(QtCore.QRect(10, 50, 991, 581))
        self.mplWidget.setObjectName("mplWidget")
        self.peakBox = QtWidgets.QGroupBox(self.centralwidget)
        self.peakBox.setGeometry(QtCore.QRect(1020, 80, 241, 501))
        self.peakBox.setObjectName("peakBox")
        self.tableWidget = QtWidgets.QTableWidget(self.peakBox)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 221, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 91, 17))
        self.label.setObjectName("label")
        self.computeButton = QtWidgets.QPushButton(self.centralwidget)
        self.computeButton.setGeometry(QtCore.QRect(1040, 10, 171, 25))
        self.computeButton.setObjectName("computeButton")
        self.formulaEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.formulaEdit.setGeometry(QtCore.QRect(130, 10, 871, 25))
        self.formulaEdit.setObjectName("formulaEdit")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(1020, 590, 241, 25))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.saveButton = QtWidgets.QPushButton(self.splitter)
        self.saveButton.setObjectName("saveButton")
        self.exportButton = QtWidgets.QPushButton(self.splitter)
        self.exportButton.setObjectName("exportButton")
        self.YLogscaleCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.YLogscaleCheckBox.setGeometry(QtCore.QRect(1040, 50, 121, 23))
        self.YLogscaleCheckBox.setObjectName("YLogscaleCheckBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IsoMol"))
        self.peakBox.setTitle(_translate("MainWindow", "Peaks:"))
        self.label.setText(_translate("MainWindow", "Brute formula:"))
        self.computeButton.setText(_translate("MainWindow", "Compute"))
        self.saveButton.setText(_translate("MainWindow", "Save .png"))
        self.exportButton.setText(_translate("MainWindow", "Export .csv"))
        self.YLogscaleCheckBox.setText(_translate("MainWindow", "Use logscale Y"))
